import localFont from "next/font/local";
import type { Metadata } from "next";
import { Caveat } from "next/font/google";
import "./globals.css";
import { Footer } from "../components/custom/Footer/Footer";
import { Header } from "../components/custom/Header/Header";
import QueryProvider from "./providers/query-provider";

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "block",
});

const dancePartner = localFont({
  src: "../fonts/dance_partner.woff2",
  variable: "--font-dance-partner",
  display: "block",
});

const involveMedium = localFont({
  src: "../fonts/involve_medium.woff2",
  variable: "--font-involve-medium",
  display: "block",
});

export const metadata: Metadata = {
  title: "Boyarinova Beauty Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${involveMedium.variable} ${dancePartner.variable} ${caveat.variable} antialiased`}
      >
        <Header />
        <QueryProvider>{children}</QueryProvider>
        <Footer />
      </body>
    </html>
  );
}
